// automatically generated by the FlatBuffers compiler, do not modify

package messaging;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.BooleanVector;
import com.google.flatbuffers.ByteVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.DoubleVector;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.FloatVector;
import com.google.flatbuffers.IntVector;
import com.google.flatbuffers.LongVector;
import com.google.flatbuffers.ShortVector;
import com.google.flatbuffers.StringVector;
import com.google.flatbuffers.Struct;
import com.google.flatbuffers.Table;
import com.google.flatbuffers.UnionVector;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class VariantPayload extends Table {
  public static void ValidateVersion() { Constants.FLATBUFFERS_23_1_21(); }
  public static VariantPayload getRootAsVariantPayload(ByteBuffer _bb) { return getRootAsVariantPayload(_bb, new VariantPayload()); }
  public static VariantPayload getRootAsVariantPayload(ByteBuffer _bb, VariantPayload obj) { _bb.order(ByteOrder.LITTLE_ENDIAN); return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb)); }
  public void __init(int _i, ByteBuffer _bb) { __reset(_i, _bb); }
  public VariantPayload __assign(int _i, ByteBuffer _bb) { __init(_i, _bb); return this; }

  public String payloadType() { int o = __offset(4); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer payloadTypeAsByteBuffer() { return __vector_as_bytebuffer(4, 1); }
  public ByteBuffer payloadTypeInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 4, 1); }
  public String value() { int o = __offset(6); return o != 0 ? __string(o + bb_pos) : null; }
  public ByteBuffer valueAsByteBuffer() { return __vector_as_bytebuffer(6, 1); }
  public ByteBuffer valueInByteBuffer(ByteBuffer _bb) { return __vector_in_bytebuffer(_bb, 6, 1); }

  public static int createVariantPayload(FlatBufferBuilder builder,
      int payloadTypeOffset,
      int valueOffset) {
    builder.startTable(2);
    VariantPayload.addValue(builder, valueOffset);
    VariantPayload.addPayloadType(builder, payloadTypeOffset);
    return VariantPayload.endVariantPayload(builder);
  }

  public static void startVariantPayload(FlatBufferBuilder builder) { builder.startTable(2); }
  public static void addPayloadType(FlatBufferBuilder builder, int payloadTypeOffset) { builder.addOffset(0, payloadTypeOffset, 0); }
  public static void addValue(FlatBufferBuilder builder, int valueOffset) { builder.addOffset(1, valueOffset, 0); }
  public static int endVariantPayload(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) { __reset(_vector, _element_size, _bb); return this; }

    public VariantPayload get(int j) { return get(new VariantPayload(), j); }
    public VariantPayload get(VariantPayload obj, int j) {  return obj.__assign(__indirect(__element(j), bb), bb); }
  }
}

