// automatically generated by the FlatBuffers compiler, do not modify

package messaging;

import com.google.flatbuffers.BaseVector;
import com.google.flatbuffers.Constants;
import com.google.flatbuffers.FlatBufferBuilder;
import com.google.flatbuffers.Table;
import java.nio.ByteBuffer;
import java.nio.ByteOrder;

@SuppressWarnings("unused")
public final class VariantEntry extends Table {
  public static void ValidateVersion() {
    Constants.FLATBUFFERS_23_1_21();
  }

  public static VariantEntry getRootAsVariantEntry(ByteBuffer _bb) {
    return getRootAsVariantEntry(_bb, new VariantEntry());
  }

  public static VariantEntry getRootAsVariantEntry(ByteBuffer _bb, VariantEntry obj) {
    _bb.order(ByteOrder.LITTLE_ENDIAN);
    return (obj.__assign(_bb.getInt(_bb.position()) + _bb.position(), _bb));
  }

  public void __init(int _i, ByteBuffer _bb) {
    __reset(_i, _bb);
  }

  public VariantEntry __assign(int _i, ByteBuffer _bb) {
    __init(_i, _bb);
    return this;
  }

  public String key() {
    int o = __offset(4);
    return o != 0 ? __string(o + bb_pos) : null;
  }

  public ByteBuffer keyAsByteBuffer() {
    return __vector_as_bytebuffer(4, 1);
  }

  public ByteBuffer keyInByteBuffer(ByteBuffer _bb) {
    return __vector_in_bytebuffer(_bb, 4, 1);
  }

  public long value() {
    int o = __offset(6);
    return o != 0 ? (long) bb.getInt(o + bb_pos) & 0xFFFFFFFFL : 0L;
  }

  public static int createVariantEntry(FlatBufferBuilder builder, int keyOffset, long value) {
    builder.startTable(2);
    VariantEntry.addValue(builder, value);
    VariantEntry.addKey(builder, keyOffset);
    return VariantEntry.endVariantEntry(builder);
  }

  public static void startVariantEntry(FlatBufferBuilder builder) {
    builder.startTable(2);
  }

  public static void addKey(FlatBufferBuilder builder, int keyOffset) {
    builder.addOffset(0, keyOffset, 0);
  }

  public static void addValue(FlatBufferBuilder builder, long value) {
    builder.addInt(1, (int) value, (int) 0L);
  }

  public static int endVariantEntry(FlatBufferBuilder builder) {
    int o = builder.endTable();
    return o;
  }

  public static final class Vector extends BaseVector {
    public Vector __assign(int _vector, int _element_size, ByteBuffer _bb) {
      __reset(_vector, _element_size, _bb);
      return this;
    }

    public VariantEntry get(int j) {
      return get(new VariantEntry(), j);
    }

    public VariantEntry get(VariantEntry obj, int j) {
      return obj.__assign(__indirect(__element(j), bb), bb);
    }
  }
}
