name: Publish WASM

on:
  workflow_dispatch:
    inputs:
      version:
        description: New version semver
        required: true
        type: string
      tag:
        description: NPM tag
        required: false
        type: string
        default: 'latest'

jobs:
  build-and-publish-wasm:
    runs-on: ubuntu-latest
    steps:
      - name: Generate token
        id: generate-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.UNLEASH_BOT_APP_ID }}
          private-key: ${{ secrets.UNLEASH_BOT_PRIVATE_KEY }}

      - uses: actions/checkout@v4
        with:
          token: ${{ steps.generate-token.outputs.token }}

      - name: Setup git config
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: 'https://registry.npmjs.org'

      - name: Set version variable
        run: |
          PACKAGE_VERSION=$(node -p "'${{ inputs.version }}'.replace(/^v/, '')")
          echo "PACKAGE_VERSION=$PACKAGE_VERSION" >> $GITHUB_ENV

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0

      - name: Build WASM
        run: |
          cd yggdrasilwasm
          wasm-pack build --target web --scope unleash

      - name: 🔖 Create version
        run: yarn version --new-version ${PACKAGE_VERSION} --no-commit-hooks
        working-directory: yggdrasilwasm/pkg

      - name: 🚢 Push to git
        run: |
          git push origin ${{ github.ref_name }}
          git push --tags

      - name: 📦️ Publish to NPM
        run: npm publish --access public --tag ${{ inputs.tag }}
        working-directory: yggdrasilwasm/pkg
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
