name: Publish Java
on:
  workflow_dispatch:

jobs:

  publish_jars:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install rust
        run: |
          rustup set auto-self-update disable
          rustup toolchain install stable --profile default
          rustup show
      - name: Rust cache
        uses: Swatinem/rust-cache@v2
      - name: Install wasm-target
        run: rustup target add wasm32-unknown-unknown
      - name: Build yggdrasil wasm
        working-directory: pure-wasm
        run: cargo build --release --target wasm32-unknown-unknown

      - name: Publish to Maven Central Portal
        env:
          ORG_GRADLE_PROJECT_signingKey: ${{ secrets.GPG_PRIVATE_KEY }}
          ORG_GRADLE_PROJECT_signingPassphrase: ${{ secrets.GPG_PASSPHRASE }}
          ORG_GRADLE_PROJECT_mavenCentralToken: ${{ secrets.MAVEN_CENTRAL_TOKEN }}
        run: |
          cd java-engine
          ./gradlew publishToMavenCentralPortal
