name: .NET Publish
on:
  workflow_dispatch:

jobs:

  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # - name: Download yggdrasilffi binaries
      #   run: |
      #     for rid in linux-x64 linux-arm64 win-x64 win-arm64 osx-x64 osx-arm64; do
      #       mkdir -p dotnet-engine/runtimes/${rid}/native
      #       echo "Downloading artifact for $rid"
      #       if ! gh run download --name $rid --dir dotnet-engine/runtimes/${rid}/native; then
      #         echo "Failed to download artifact for $rid, continuing..."
      #       fi
      #     done
      #   env:
      #     GH_TOKEN: ${{ github.token }}

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      - name: Extract Yggdrasil Core Version
        id: extract_ffi_version
        run: |
          sudo apt-get install -y xmlstarlet
          cd dotnet-engine/Yggdrasil.Engine
          CORE_VERSION=$(xmlstarlet sel -t -v "/Project/PropertyGroup/YggdrasilCoreVersion" -n Yggdrasil.Engine.csproj)
          echo "FFI Library Version: $CORE_VERSION"
          echo "CORE_VERSION=$CORE_VERSION" >> $GITHUB_ENV

      - name: Restore dependencies
        run: |
          cd dotnet-engine
          dotnet restore dotnet-engine.sln

      - name: Build
        run: |
          cd dotnet-engine
          dotnet build dotnet-engine.sln -c Release --no-restore

      - name: Pack
        run: |
          cd dotnet-engine
          dotnet pack dotnet-engine.sln -c Release --no-build --no-restore

      - name: Check package size
        run: |
          cd dotnet-engine
          ls -lh Yggdrasil.Engine/bin/Release/*nupkg

      # - name: Upload package artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: yggdrasil-nuget
      #     path: dotnet-engine/Yggdrasil.Engine/bin/Release/*nupkg

      # - name: Publish package
      #   run: |
      #     cd dotnet-engine
      #     dotnet nuget push Yggdrasil.Engine/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
