name: Build Ruby
on:
  workflow_dispatch:

jobs:
  no-op:
    runs-on: ubuntu-latest
    steps:
      - run: echo "No-op job to satisfy dependency requirements."

  build_single_binary_gems:
    needs: build-binaries
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            binary: libyggdrasilffi_x86_64.so
          - os: ubuntu-latest
            binary: libyggdrasilffi_arm64.so
            platform: arm-linux
          - os: ubuntu-latest
            binary: libyggdrasilffi_aarch64.so
            platform: aarch64-linux
          - os: windows-latest
            binary: libyggdrasilffi_x86_64.dll
          - os: windows-latest
            platform: arm64-mingw32
            binary: libyggdrasilffi_arm64.dll
          - os: macos-13
            binary: libyggdrasilffi_x86_64.dylib
            platform: x86_64-darwin
          - os: macos-latest
            binary: libyggdrasilffi_arm64.dylib
            platform: arm64-darwin

    steps:
      - uses: actions/checkout@v4

      - name: Overwrite Build Platform
        if: matrix.platform != ''
        run: echo "YGG_BUILD_PLATFORM=${{ matrix.platform }}" >> $GITHUB_ENV

      - name: Download Compiled Binaries
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.binary }}
          path: ruby-engine/lib
          merge-multiple: true

      - name: Build and Publish Linux Gem
        run: |
          cd ruby-engine
          gem build yggdrasil-engine.gemspec
          # gem push *.gem
        working-directory: ${{ github.workspace }}
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEMS_PUBLISH_KEY }}

  build_jruby_gems:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: 8
            ruby: jruby-9.2
          - java: 11
            ruby: jruby-9.3
          - java: 17
            ruby: jruby-9.4
          - java: 21
            ruby: jruby-9.4

    needs: build-binaries
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Setup JRuby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}

      - name: Download Compiled Binaries
        uses: actions/download-artifact@v4
        with:
          path: ruby-engine/lib
          merge-multiple: true

      - name: Build and Publish Gem for JRuby
        run: |
          cd ruby-engine
          gem build yggdrasil-engine.gemspec
          # gem push *.gem
        working-directory: ${{ github.workspace }}
        env:
          GEM_HOST_API_KEY: ${{ secrets.GEMS_PUBLISH_KEY }}
