name: Publish WASM

on:
  workflow_dispatch:
    inputs:
      version:
        description: New version semver
        required: true
        type: string
      tag:
        description: NPM tag
        required: false
        type: string
        default: 'latest'

jobs:
  build-wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Install wasm-pack
        uses: jetli/wasm-pack-action@v0.3.0

      - name: Build WASM
        run: |
          cd yggdrasilwasm
          wasm-pack build --target web --scope unleash

  publish-wasm:
    needs: [build-wasm]
    uses: Unleash/.github/.github/workflows/npm-release.yml@v2.0.0
    with:
      version: ${{ github.event.inputs.version }}
      tag: ${{ github.event.inputs.tag }}
      working-directory: yggdrasilwasm/pkg
      setup-command: "echo 'Skipping setup. Already done.'"
    secrets:
      NPM_ACCESS_TOKEN: ${{ secrets.NPM_TOKEN }}
      UNLEASH_BOT_APP_ID: ${{ secrets.UNLEASH_BOT_APP_ID }}
      UNLEASH_BOT_PRIVATE_KEY: ${{ secrets.UNLEASH_BOT_PRIVATE_KEY }}
